---
- name: Add admin users
  ansible.builtin.user:
    name: "{{ item.username }}"
    append: true
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/zsh
  loop: "{{ user_users }}"

- name: Configure SSH keys for admin users
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    state: present
  loop: "{{ user_users }}"

- name: Configure sudo access for admin users
  ansible.builtin.template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ item.sudoers }}"
    mode: "0440"
    owner: root
    group: root
    validate: "visudo -cf %s"
  loop: "{{ user_users }}"
