---
- name: Create persistent app storage directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/storage/app/public"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create persistent log storage directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/storage/logs"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create persistent framework cache storage directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/storage/framework/cache"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create persistent framework session storage directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/storage/framework/sessions"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create persistent framework views storage directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/storage/framework/views"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create persistent config directory
  ansible.builtin.file:
    path: "/home/{{ user }}/persistent/config"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create env file
  ansible.builtin.template:
    src: templates/env.j2
    dest: "/home/{{ user }}/persistent/config/env"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Create supervisor configuration
  become: true
  ansible.builtin.template:
    src: templates/supervisor.j2
    dest: "/etc/supervisor/conf.d/{{ app_name }}-worker.conf"
    mode: "0644"
  when: horizon sameas true

- name: Define scheduler cron job
  ansible.builtin.cron:
    job: "php /home/{{ user }}/current/artisan schedule:run >> /dev/null 2>&1"
    user: "{{ user }}"
    name: "{{ user }}-horizon"
