---
- name: Change root password
  ansible.builtin.user:
    name: root
    password: "{{ root_passwd | password_hash('sha512') }}"

- name: Lock root user account
  ansible.builtin.command: passwd -l root
  changed_when: false

- name: Remove sudo group rights
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^%sudo"
    state: absent
    validate: "visudo -cf %s"
    mode: "0440"
    owner: root
    group: root
