---
- name: Provision web application
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: app
    - role: nginx
    - role: php
      when: php is sameas true
    - role: laravel
      when: laravel is sameas true
    - role: mysql
      when: mysql is sameas true
