---
- name: Create scripts directory
  ansible.builtin.file:
    path: "/home/forge/scripts"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Create reload script
  ansible.builtin.template:
    src: files/reload.sh
    dest: "/home/forge/scripts/reload.sh"
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Give permissions to reload php and supervisor
  ansible.builtin.template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/supervisor"
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"
