---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"
  loop:
    - "/home/forge/{{ website }}/releases"
    - "/home/forge/{{ website }}/persistent"

- name: Create persistent app storage directory
  ansible.builtin.file:
    path: "/home/forge/{{ website }}/persistent/storage/app/public"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Create persistent log storage directory
  ansible.builtin.file:
    path: "/home/forge/{{ website }}/persistent/storage/logs"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Create persistent framework cache storage directory
  ansible.builtin.file:
    path: "/home/forge/{{ website }}/persistent/storage/framework/cache"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Create persistent framework session storage directory
  ansible.builtin.file:
    path: "/home/forge/{{ website }}/persistent/storage/framework/sessions"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"

- name: Create persistent framework views storage directory
  ansible.builtin.file:
    path: "/home/forge/{{ website }}/persistent/storage/framework/views"
    state: directory
    owner: "forge"
    group: "forge"
    mode: "0755"
