---
- name: Deploy nginx site config
  ansible.builtin.template:
    src: templates/subdomain.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_uri }}.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  when: not ssl

- name: Deploy nginx site ssl config
  ansible.builtin.template:
    src: templates/subdomain-ssl.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_uri }}.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  when: ssl

- name: Activate nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_uri }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_uri }}.conf"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
