---
- name: Create /tmp/letsencrypt directory
  ansible.builtin.file:
    path: /tmp/letsencrypt/.well-known
    state: directory
    mode: "0777"

- name: Create acme-challenge directory
  ansible.builtin.file:
    path: /tmp/letsencrypt/.well-known/acme-challenge
    state: directory
    mode: "0777"

- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - "/home/{{ user }}/logs"
    - "/home/{{ user }}/releases"
    - "/home/{{ user }}/persistent"
    - "/home/{{ user }}/scripts"

- name: Create log files
  ansible.builtin.file:
    path: "/home/{{ user }}/logs/{{ item }}"
    state: touch
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  loop:
    - error.log
    - access.log
    - slowlog.log
