---
- name: Create app user
  ansible.builtin.user:
    name: "{{ user }}"
    password: '{{ passwd | password_hash("sha512") }}'
    shell: /bin/zsh
    state: present
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: .ssh/github
    ssh_key_comment: digital@actstar.com

- name: Add ssh config to app user
  ansible.builtin.copy:
    src: files/ssh_config
    dest: "/home/{{ user }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

- name: Enable remote access to app user
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ item }}"
  loop:
    - "{{ lookup('file', 'd.stinglhamber.pub') }}"
    - "{{ lookup('file', 'm.merah.pub') }}"
