---
- name: Set root password
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_passwd }}"
    state: present
    login_password: "{{ mysql_root_passwd }}"
  loop:
    - localhost
    - 127.0.0.1
    - ::1

- name: Reload privilege tables
  ansible.builtin.command: >
    mysql -ne "FLUSH PRIVILEGES"
    -uroot -p"{{ mysql_root_passwd }}"
  changed_when: false

- name: Remove anonymous users
  ansible.builtin.command: >
    mysql -ne "DELETE FROM mysql.user WHERE User=''"
    -uroot -p"{{ mysql_root_passwd }}"
  changed_when: false

- name: Disallow root login remotely
  ansible.builtin.command: >
    mysql -ne "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    -uroot -p"{{ mysql_root_passwd }}"
  changed_when: false

- name: Remove test database
  ansible.builtin.command: >
    mysql -ne "DROP DATABASE IF EXISTS test; DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    -uroot -p"{{ mysql_root_passwd }}"
  changed_when: false
  ignore_errors: true

- name: Reload privilege tables
  ansible.builtin.command: >
    mysql -ne "FLUSH PRIVILEGES"
    -uroot -p"{{ mysql_root_passwd }}"
  changed_when: false
  notify: Restart MySQL
