---
- name: Provision web server
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: server_base
    - role: user
    - role: ssh
    - role: security
    - role: nginx
    - role: php
      when: php is sameas true
    - role: redis
      when: redis is sameas true
    - role: nodejs
      when: nodejs is sameas true
    - role: mysql
      when: mysql is sameas true
