---
- name: Install Composer
  ansible.builtin.get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: "0755"
    owner: root
    group: root

- name: Update Composer
  ansible.builtin.command: /usr/local/bin/composer self-update
  changed_when: false
