---
- name: Remove default php-fpm pool
  ansible.builtin.file:
    path: /etc/php/8.4/fpm/pool.d/www.conf
    state: absent
  notify:
    - Restart PHP8.4-FPM

- name: Create php-fpm pool directory
  ansible.builtin.file:
    path: /etc/php/8.4/fpm/pool.d
    state: directory
    owner: www-data
    mode: "0644"

- name: Create php-fpm log directory
  ansible.builtin.file:
    path: /var/log/php-fpm
    state: directory
    owner: www-data
    mode: "0644"

- name: Create php log directory
  ansible.builtin.file:
    path: /var/log/php
    state: directory
    owner: www-data
    mode: "0644"

- name: Create php upload directory
  ansible.builtin.file:
    path: /var/lib/php/upload
    state: directory
    owner: www-data
    mode: "0644"

- name: Create php session directory
  ansible.builtin.file:
    path: /var/lib/php/session
    state: directory
    owner: www-data
    mode: "0644"

- name: Modify php.ini settings
  ansible.builtin.copy:
    src: files/php.ini
    dest: /etc/php/8.4/fpm/php.ini
    mode: "0644"
  notify:
    - Restart PHP8.4-FPM
