---
- name: Get PHP GPG key
  ansible.builtin.get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    mode: "0644"

- name: Create PHP repository configuration
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/php.list
    src: files/php.list
    mode: "0644"
    owner: root
    group: root

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install PHP packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - php8.4
    - php8.4-cli
    - php8.4-json
    - php8.4-mysql
    - php8.4-xml
    - php8.4-mbstring
    - php8.4-curl
    - php8.4-zip
    - php8.4-gd
    - php8.4-imagick
    - php8.4-fpm
  notify: Start PHP-FPM
