---
- name: Implement asset caching
  ansible.builtin.copy:
    src: files/assets-caching.conf
    dest: "/etc/nginx/forge-conf/{{ website }}/server/assets-caching.conf"
    owner: root
    group: root
    mode: "0644"

- name: Add security headers
  ansible.builtin.copy:
    src: files/headers.conf
    dest: "/etc/nginx/forge-conf/{{ website }}/server/headers.conf"
    owner: root
    group: root
    mode: "0644"
