---
- name: Hostname
  ansible.builtin.include_tasks: hostname.yml
- Name: Install packages
  ansible.builtin.include_tasks: packages.yml
- Name: Timezone
  ansible.builtin.include_tasks: timezone.yml
- Name: SSL Certifiate
  ansible.builtin.include_tasks: ssl_certificate.yml
