---
- name: Perform Safe Upgrade
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true

- name: Install Server Basics
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ packages }}"

- name: Add Periodic Configuration
  ansible.builtin.copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: "0644"

- name: Add Unattended Upgrade Configuration
  ansible.builtin.copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  notify: Restart Unattended Upgrades
